@server = localhost
@port = 3000
@basepath = /api

### Test
http://{{server}}:{{port}}{{basepath}}/test
Content-Type: application/json

### Greetings

http://{{server}}:{{port}}/api/greetings
Content-Type: application/json

{
    "name": "Vereb"
}